package com.charbhujatech.cloudmart.enums;

public enum OrderStatus {
    AWAITING_PAYMENT, PENDING, CONFIRMED, PROCESSING, SHIPPED, OUT_FOR_DELIVERY, DELIVERED
    , RETURN_REQUESTED,RETURN_ACCEPTED, RETURNED_AND_REFUNDED, REJECTED

}
